dist/index.js, src/utils/get-languages.ts, src/utils/strings.ts
Checklist:
Closes #XXXXX
A couple of incorrect paths were causing issues in my testing repository.
=> fix: bad paths

.github/workflows/require-dist.yml
Checklist:
Closes #XXXXX
The action fails if all you do is upload a config, because the path matches `/src/config` but no changes are made to the code so no updates propagate to `/dist/index.js`.
@ShaunSHamilton broke it 🙃
=> fix: ignore configs folder

dist/configs/rust-in-replit.yml, src/configs/rust-in-replit.yml
Checklist:
Closes #XXXXX
Action threw an error with current config. Crowdin documentation shows use of wildcard is okay but appears to expect extension? This should resolve it
=> fix: use extensions maybe?

dist/index.js, src/plugins/hide-curriculum-strings.ts
=> fix: handle subdirectory

dist/index.js, src/plugins/hide-curriculum-strings.ts
Checklist:
Closes #XXXXX
Amazing that I forgot this wow.
=> fix: actually slice the path like I meant to

src/index.ts
Checklist:
Closes #XXXXX
Uses Camperbot's credentials as a fallback if credentials are not passed through the secrets.
=> feat: add fallback values for email+user

dist/configs/news.yml, src/configs/news.yml
Checklist:
Closes #XXXXX
Adds the configuration to allow us to integrate the news UI with crowdin
=> feat: add news config

dist/configs/curriculum.yml, src/configs/curriculum.yml
=> fix: js 2022 path

src/configs/rust-in-replit.yml
Checklist:
Related: https://github.com/freeCodeCamp/Rust-In-Replit/pull/28
@naomi-lgbt I am not sure if this will work? Specifically, I have `spanish`, but we have `espanol` on `freeCodeCamp/freeCodeCamp`...
Also, what happens to the translated content on Crowdin now? Is this a major problem, or something Crowdin will seamlessly handle?
=> chore(configs): update rust-in-replit  directory

dist/index.js, package-lock.json, package.json, src/plugins/pull-request.ts
=> fix: skip PR creation if commit not present

dist/configs/news.yml, src/configs/news.yml
=> fix: ignore redirects.json in news config

dist/configs/mobile.yml, src/configs/mobile.yml
=> feat: add config for mobile

dist/configs/curriculum.yml, dist/configs/docs.yml, src/configs/curriculum.yml, src/configs/docs.yml
Checklist:
Closes #XXXXX
Crowdin support says this should resolve the context issue.
=> feat: specific markdown type

dist/configs/docs.yml, dist/index.js, src/configs/docs.yml
=> feat: new directory structure

dist/index.js, src/plugins/convert-chinese.ts
=> feat: support single file paths for chinese plugin

dist/index.js, src/utils/strings.ts
=> feat: add new headings for english challenges

dist/index.js, src/utils/strings.ts
=> feat: also hide assignment header

dist/index.js
Checklist:
The build wasn't updated when the lowercase-directories plugin was changed, so https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/9350098146/job/25732841477 happened since it uses `FILE_PATH` not `FILE_PATHS
`
=> build: add lowercase-directories update to dist

.github/workflows/node-ci.yml
Checklist:
Should pass once https://github.com/freeCodeCamp/crowdin-action/pull/39 is in, since main's src and dist are out of sync and that PR fixes it.
=> ci: check dist is in sync with src

dist/index.js, src/index.ts
Checklist:
Ref: https://github.com/freeCodeCamp/freeCodeCamp/actions/runs/9462312913/job/26064988560
=> fix: FILE_PATH is a string, not JSON

dist/index.js, src/utils/strings.ts
Checklist:
Closes #XXXXX
I used `pnpm run package` to reflect the change to dist/index.js.
=> feat: hide transcript header

dist/index.js, src/utils/strings.ts
Had some headings on crowdin which were getting translated.
Checklist:
Closes #XXXXX
Ref: https://github.com/freeCodeCamp/freeCodeCamp/pull/59001 and https://github.com/freeCodeCamp/freeCodeCamp/pull/60921
=> feat: add more headings
